### ISSUE TITLE
Bad sentence construction

### ISSUE THREAD

**Issue by Haywayaheadshot** [Haywayaheadshot/abu-the-portfolio#18]
### Bug description
- The construction of the sentences below is not correct.
> https://github.com/Haywayaheadshot/abu-the-portfolio/blob/a5a1e14c11739fa148d945a782ae9d9192e4e1bf/src/pages/About.js#L22-L31

### Suggested fix
- Rewrite the whole paragraph again.
- Make sure to also correct it on Linkedin.
- You could re-write the whole section to sell you better

**Comment by Pragyan14** [comment]
I want to work on this issue please assign me this issue.
