### ISSUE TITLE
Use Google font

### ISSUE THREAD

**Issue by Haywayaheadshot** [Haywayaheadshot/abu-the-portfolio#21]
- Add other Google fonts to style.md and decide which one to use
- Cartoonish font looks great for the logo

**Comment by Sukrittt** [comment]
- I have font suggestions, but those are not google fonts.
- It will be a `.otf` or `.ttf` files which can be added in the CSS using `@font-face` syntax.
- If it is okay, then I can make a pull request to add these files and implement them in your website.

**Comment by Haywayaheadshot** [comment]
@Sukrittt Sure. I will assign you the task
