### ISSUE TITLE
Add live site URL in your project description

### ISSUE THREAD

**Issue by Sukrittt** [Haywayaheadshot/abu-the-portfolio#23]
- Just a suggestion, that it is better to add your live site URL in the about section of your repository.
- In this way people can access your website easily.

**Comment by Haywayaheadshot** [comment]
@Sukrittt Do you mean on my GitHub profile or on this project?

**Comment by Sukrittt** [comment]
On this project

**Comment by Haywayaheadshot** [comment]
@Sukrittt I believe I have added "Live Demo" and "Source Code" links to every project as you can see below.

If that is not what you meant, could you please explain further?

https://github.com/Haywayaheadshot/abu-the-portfolio/blob/aad7e4dd6be3d2d307949e423954800182330ab2/src/components/dep/Project.js#L44-L58

**Comment by Sukrittt** [comment]
Sorry I wasn't clear before. By adding link in the project, I meant adding it in the project description.

* If you click on the gear icon, you have 3 fields to fill - description, website URL and tags.
* Fill in the URL field.

### Image Reference
![Screenshot 2023-04-13 180829](https://user-images.githubusercontent.com/106579296/231789524-accd0b6d-51ba-4660-b10e-bfd311f05cdb.png)

**Comment by Haywayaheadshot** [comment]
Oh I see. Thank you very much. That is a great idea.
